# config.yaml
# Define objective: 'maximize' or 'minimize' a given metric
objective:
  type: maximize       # Change to 'minimize' for cost-driven missions
  metric: coverage_time  # Metric to optimize (e.g., coverage_time, cost)

# Global constraints for the mission
constraints:
  max_mass: 500       # [kg] total mass limit
  max_cost: 50        # [$M] total cost limit

# Components and their available options
components:
  payload:
    options:
      - name: camera_A
        mass: 50
        cost: 5
        coverage_time: 2.5
      - name: camera_B
        mass: 75
        cost: 7
        coverage_time: 3.0
      - name: camera_C     # add here without modifying main.py
        mass: 60
        cost: 6
        coverage_time: 2.8
  power_system:
    options:
      - name: solar_panel_small
        mass: 100
        cost: 2
        power_output: 1.5
      - name: solar_panel_large
        mass: 200
        cost: 4
        power_output: 3.5
  comms:
    options:
      - name: X_band
        mass: 20
        cost: 1
        data_rate: 100
      - name: Ka_band
        mass: 30
        cost: 2
        data_rate: 200

# Notes:
# - To adapt for a new year, update 'objective', 'constraints', or add/remove 'components'.
# - Ensure metric keys exist in each option entry (e.g., coverage_time, mass, cost).
